# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

#
# DO NOT EDIT THIS FILE.
#
# This file contains the default values of all build-time configuration
# variables. EDIT user.mk TO OVERRIDE THESE VALUES.
#

#
# compiler.mk
#

# Name prefix of the compiler toolchain
PREFIX ?= arm-none-eabi

#
# consts.mk
#

# Path to the TI CC3200 SDK
SDK_PATH ?= $(ABS_TOPDIR)/external/cc3200-sdk
